import { Button } from "../views/button/button.ts";
import { ContentList } from "../views/split-view/content-list.ts";
import { Image } from "../views/image/image.ts";
import { Outline } from "../views/outline/outline.ts";
import { ScrollView } from "../views/scroll-view/scroll-view.ts";
import { SideBar } from "../views/split-view/sidebar.ts";
import { Slider } from "../views/slider/slider.ts";
import SplitView from "../views/split-view/split-view.ts";
import { TableCell } from "../views/table/table-cell.ts";
import { Text } from "../views/text/text.ts";
import { View } from "../views/view/view.ts";
import { Window } from "../views/window/window.ts";
import { WebView } from "../views/webview/webview.ts";
import { registerGlobalDocument } from "./environment.ts";
import { Checkbox } from "../views/checkbox/checkbox.ts";
import { ComboBox } from "../views/combobox/combobox.ts";
import { Progress } from "../views/progress/progress.ts";
import { Toolbar } from "../views/toolbar/toolbar.ts";
import { ToolbarItem } from "../views/toolbar/toolbar-item.ts";
import { ToolbarToggleSidebar } from "../views/toolbar/toolbar-toggle-sidebar.ts";
import { ToolbarSidebarTrackingSeparator } from "../views/toolbar/toolbar-sidebar-tracking-separator.ts";
import { ToolbarFlexibleSpace } from "../views/toolbar/toolbar-flexible-space.ts";
Button.register();
Checkbox.register();
ComboBox.register();
ContentList.register();
Image.register();
Outline.register();
ScrollView.register();
SplitView.register();
SideBar.register();
Slider.register();
TableCell.register();
Text.register();
WebView.register();
Window.register();
View.register();
Progress.register();
Toolbar.register();
ToolbarItem.register();
ToolbarToggleSidebar.register();
ToolbarSidebarTrackingSeparator.register();
ToolbarFlexibleSpace.register();
registerGlobalDocument();
